### ISSUE TITLE
Server should not exit if connection to LDAP goes down

### ISSUE THREAD

**Issue by ralekseenkov** [Aptomi/aptomi#185]
docker stop 96913e2c6a9a

INFO[2967] (enforce-573) No changes, policy gen 14
panic: LDAP Result Code 200 "Network Error": dial tcp 127.0.0.1:10389: getsockopt: connection refused

goroutine 67985 [running]:
github.com/Aptomi/aptomi/pkg/external/users.(*UserLoaderFromLDAP).LoadUsersAll(0xc420052f00, 0x0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/external/users/user_loader_from_ldap.go:49 +0x300
github.com/Aptomi/aptomi/pkg/external/users.(*UserLoaderFromLDAP).LoadUserByName(0xc420052f00, 0xc4227d71c8, 0x4, 0xc422dc0fc0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/external/users/user_loader_from_ldap.go:63 +0x2b
github.com/Aptomi/aptomi/pkg/external/users.(*UserLoaderMultipleSources).LoadUserByName(0xc42073bcc0, 0xc4227d71c8, 0x4, 0xc4225b9a40)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/external/users/user_loader_multiple_sources.go:34 +0x81
github.com/Aptomi/aptomi/pkg/engine/resolve.(*PolicyResolver).newResolutionNode(0xc4209ca540, 0xc423d99440, 0x10043a4)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/resolve/policy_resolver_node.go:76 +0x66
github.com/Aptomi/aptomi/pkg/engine/resolve.(*PolicyResolver).resolveDependency(0xc4209ca540, 0xc423d99440, 0x0, 0x0, 0xffffffffffffffff)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/resolve/policy_resolver.go:125 +0x35
github.com/Aptomi/aptomi/pkg/engine/resolve.(*PolicyResolver).ResolveAllDependencies.func1(0xc4209ca540, 0xc423fe0000, 0xc420d88800, 0xc423d99440)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/resolve/policy_resolver.go:91 +0x39
created by github.com/Aptomi/aptomi/pkg/engine/resolve.(*PolicyResolver).ResolveAllDependencies
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/resolve/policy_resolver.go:90 +0x12d

**Comment by ralekseenkov** [comment]
fixed
