### ISSUE TITLE
Implement validation for k8s cluster config

### ISSUE THREAD

**Issue by ralekseenkov** [Aptomi/aptomi#225]
When uploading policy with k8s clusters, their configs should be validated.

Otherwise, you can upload any k8s clusters into Aptomi (even with invalid configs) and it will result in errors in runtime. E.g. like this one:
```
ERRO[4754] (enforce-918-apply) error while applying action 'action-component-create/cluster-us-east#main#twitter_stats#prod#tweeviz': panic: runtime error: invalid memory address or nil pointer dereference
goroutine 16 [running]:
runtime/debug.Stack(0xc421c69010, 0x29b9f00, 0x3f69960)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/Aptomi/aptomi/pkg/engine/apply.(*EngineApply).executeAction.func1(0xc421c69af0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/apply/engine_apply.go:103 +0x60
panic(0x29b9f00, 0x3f69960)
	/usr/local/Cellar/go/1.9.3/libexec/src/runtime/panic.go:491 +0x283
github.com/Aptomi/aptomi/vendor/k8s.io/client-go/kubernetes.NewForConfig(0x0, 0x2b52920, 0xc42189d780, 0x2b52920)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/vendor/k8s.io/client-go/kubernetes/clientset.go:420 +0x4e
github.com/Aptomi/aptomi/pkg/plugin/helm.(*clusterCache).newKubeClient(0xc420649d80, 0xc421dd25a0, 0xc4209dac90, 0xc420649d80, 0x0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/plugin/helm/k8s_util.go:67 +0x33
github.com/Aptomi/aptomi/pkg/plugin/helm.(*Plugin).createOrUpdate(0xc4209d8e50, 0xc421dd25a0, 0xc4218faae0, 0x1f, 0xc421264270, 0xc4209dac90, 0x1, 0xc4218faae0, 0x1f)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/plugin/helm/helm.go:40 +0x86
github.com/Aptomi/aptomi/pkg/plugin/helm.(*Plugin).Create(0xc4209d8e50, 0xc421dd25a0, 0xc4218faae0, 0x1f, 0xc421264270, 0xc4209dac90, 0x0, 0x3acdd60)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/plugin/helm/helm.go:26 +0x65
github.com/Aptomi/aptomi/pkg/engine/apply/action/component.(*CreateAction).processDeployment(0xc4209da570, 0xc421d02e60, 0xc421c69aa8, 0x2786a73)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/apply/action/component/create.go:86 +0x5e2
github.com/Aptomi/aptomi/pkg/engine/apply/action/component.(*CreateAction).Apply(0xc4209da570, 0xc421d02e60, 0xc421c69af0, 0xc420e36ae0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/apply/action/component/create.go:36 +0x3c
github.com/Aptomi/aptomi/pkg/engine/apply.(*EngineApply).executeAction(0xc421c69ee0, 0x3af1ae0, 0xc4209da570, 0xc421d02e60, 0x0, 0x0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/apply/engine_apply.go:107 +0x77
github.com/Aptomi/aptomi/pkg/engine/apply.(*EngineApply).Apply(0xc421c69ee0, 0xc421471e60, 0x3af3380, 0xc420e36ae0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/engine/apply/engine_apply.go:77 +0x24d
github.com/Aptomi/aptomi/pkg/server.(*Server).enforce(0xc4206b6bc0, 0x0, 0x0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/server/enforcer.go:112 +0xe5c
github.com/Aptomi/aptomi/pkg/server.(*Server).enforceLoop(0xc4206b6bc0, 0xc4200257b8, 0x0)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/server/enforcer.go:22 +0x45
github.com/Aptomi/aptomi/pkg/server.(*Server).startEnforcer.func1()
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/server/server.go:161 +0x2a
github.com/Aptomi/aptomi/pkg/server.(*job).start(0xc4206b4c60)
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/server/background.go:22 +0x51
created by github.com/Aptomi/aptomi/pkg/server.(*Server).runInBackground
	/Users/ralekseenkov/go/src/github.com/Aptomi/aptomi/pkg/server/background.go:27 +0xe3
```

**Comment by Frostman** [comment]
In best case, we should check that cluster is available at time when we're apply policy - before it actually saved into the DB.
