### ISSUE TITLE
Cannot apply policy to Docker for mac context

### ISSUE THREAD

**Issue by rljohnsn** [Aptomi/aptomi#349]
Install aptomi server container and local client (compact)
```
aptomictl version
DEBU[0000] Config:
debug: true
output: text
api:
  schema: http
  host: 127.0.0.1
  port: 27866
  apiprefix: api/v1
auth:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJleHAiOjE1NDUyNTc0MDcsImlhdCI6MTU0MjY2NTQwN30.ZfrRwCWinCm2RXfc8j8ioE0iuOmBCKsJjhDEgmMTDwM
http:
  timeout: 1m0s

INFO[0000] Using config file: /Users/ljohnson/.aptomi/config.yaml
INFO[0000] Client:
Git Version	Git Commit                              	Build Date
0.1.15     	63709f615372879a7170f274cc9e5c76fee41d1c	2018-06-25T01:56:31Z
INFO[0000] Server:
Git Version	Git Commit                              	Build Date
0.1.15     	63709f615372879a7170f274cc9e5c76fee41d1c	2018-06-25T01:54:05Z
```

Aptomi server running as container:
```
docker ps | grep aptomi
611a8dc6e064        aptomi/aptomi-test-install:xenial   "sh -c 'curl https:/…"   4 minutes ago       Up 4 minutes        0.0.0.0:27866->27866/tcp   condescending_tu
```

Following instructions [here](https://github.com/Aptomi/aptomi/blob/master/docs/k8s_docker_for_mac.md) try to add local k8s cluster to aptomi

```
kubectl config get-contexts
CURRENT   NAME                 CLUSTER                      AUTHINFO             NAMESPACE
*         docker-for-desktop   docker-for-desktop-cluster   docker-for-desktop

```
Aptomi login:
```
aptomictl login -u admin -p admin
DEBU[0000] Config:
debug: true
output: text
api:
  schema: http
  host: 127.0.0.1
  port: 27866
  apiprefix: api/v1
auth:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJleHAiOjE1NDUyNTY5NjQsImlhdCI6MTU0MjY2NDk2NH0.-RAPhotEnoDv7EX_5N7BqBqC5zefQLI0pqLnp5TBV7c
http:
  timeout: 1m0s

INFO[0000] Using config file: /Users/ljohnson/.aptomi/config.yaml
INFO[0000] Current config saved to: /Users/ljohnson/.aptomi/config.yaml.bak
INFO[0000] Config successfully updated with token
```

Generate aptomi cluster config and apply policy:
```
aptomictl gen cluster -n k8s-example -c docker-for-desktop | aptomictl policy apply -f -
DEBU[0000] Config:
debug: true
output: text
api:
  schema: http
  host: 127.0.0.1
  port: 27866
  apiprefix: api/v1
auth:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJleHAiOjE1NDUyNTc0MDcsImlhdCI6MTU0MjY2NTQwN30.ZfrRwCWinCm2RXfc8j8ioE0iuOmBCKsJjhDEgmMTDwM
http:
  timeout: 1m0s

INFO[0000] Using config file: /Users/ljohnson/.aptomi/config.yaml
DEBU[0000] Config:
debug: true
output: text
api:
  schema: http
  host: 127.0.0.1
  port: 27866
  apiprefix: api/v1
auth:
  token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJleHAiOjE1NDUyNTc0MDcsImlhdCI6MTU0MjY2NTQwN30.ZfrRwCWinCm2RXfc8j8ioE0iuOmBCKsJjhDEgmMTDwM
http:
  timeout: 1m0s

INFO[0000] Using config file: /Users/ljohnson/.aptomi/config.yaml
INFO[0000] Applying policy from stdin
INFO[0000] Generating cluster: k8s-example
FATA[0000] error while calling apply on policy: server error: error while validating cluster k8s-example of type kubernetes: error during init: Get https://localhost:6443/api/v1/nodes?timeout=10s: dial tcp 127.0.0.1:6443: connect: connection refused
```

Aptomi server in container throws the following exception:
```
172.17.0.1 - - [19/Nov/2018:22:02:44 +0000] "POST /api/v1/user/login HTTP/1.1" 200 175 "" "aptomictl"
ERRO[1453] Error while serving request: error while validating cluster k8s-example of type kubernetes: error during init: Get https://localhost:6443/api/v1/nodes?timeout=10s: dial tcp 127.0.0.1:6443: connect: connection refused  request="&{POST /api/v1/policy/noop/false/loglevel/warning HTTP/1.1 1 1 map[Accept-Encoding:[gzip] User-Agent:[aptomictl] Content-Length:[4332] Authorization:[Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJleHAiOjE1NDUyNTY5NjQsImlhdCI6MTU0MjY2NDk2NH0.-RAPhotEnoDv7EX_5N7BqBqC5zefQLI0pqLnp5TBV7c] Content-Type:[application/yaml]] 0xc42034d080 <nil> 4332 [] false 127.0.0.1:27866 map[] map[] <nil> map[] 172.17.0.1:47264 /api/v1/policy/noop/false/loglevel/warning <nil> <nil> <nil> 0xc4205bd860}"
DEBU[1453] goroutine 128 [running]:
runtime/debug.Stack(0xc400000005, 0x1891208, 0x1f)
/usr/local/Cellar/go/1.10.3/libexec/src/runtime/debug/stack.go:24 +0xa7
github.com/Aptomi/aptomi/pkg/api/middleware.(*panicHandler).ServeHTTP.func1(0xc4208f8700, 0xc42073f800, 0x19ea120, 0xc42071a380)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/pkg/api/middleware/recovery.go:31 +0x26b
panic(0x15acb60, 0xc4201d57d0)
/usr/local/Cellar/go/1.10.3/libexec/src/runtime/panic.go:502 +0x229
github.com/Aptomi/aptomi/pkg/api.(*coreAPI).handlePolicyUpdate(0xc42034e000, 0x7f56f1544368, 0xc4202181a0, 0xc4208f8700, 0xc42034d140, 0x2, 0x2)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/pkg/api/policy.go:191 +0xea7
github.com/Aptomi/aptomi/pkg/api.(*coreAPI).(github.com/Aptomi/aptomi/pkg/api.handlePolicyUpdate)-fm(0x7f56f1544368, 0xc4202181a0, 0xc4208f8700, 0xc42034d140, 0x2, 0x2)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/pkg/api/api.go:63 +0x66
github.com/Aptomi/aptomi/pkg/api.(*coreAPI).auth.func1(0x7f56f1544368, 0xc4202181a0, 0xc4208f8700, 0xc42034d140, 0x2, 0x2)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/pkg/api/auth.go:101 +0x209
github.com/Aptomi/aptomi/vendor/github.com/julienschmidt/httprouter.(*Router).ServeHTTP(0xc4206239e0, 0x7f56f1544368, 0xc4202181a0, 0xc4208f8700)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/vendor/github.com/julienschmidt/httprouter/router.go:299 +0x6c1
github.com/Aptomi/aptomi/vendor/github.com/gorilla/handlers.combinedLoggingHandler.ServeHTTP(0x19cce80, 0xc4200c6008, 0x19cb380, 0xc4206239e0, 0x19dce20, 0xc420218180, 0xc4208f8700)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/vendor/github.com/gorilla/handlers/handlers.go:77 +0x123
github.com/Aptomi/aptomi/pkg/api/middleware.(*prometheusHandler).ServeHTTP(0xc420623e30, 0x19ea120, 0xc42071a380, 0xc4208f8700)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/pkg/api/middleware/metrics.go:67 +0x11a
github.com/Aptomi/aptomi/pkg/api/middleware.(*panicHandler).ServeHTTP(0xc42073f800, 0x19ea120, 0xc42071a380, 0xc4208f8700)
/Users/ralekseenkov-mini/go/src/github.com/Aptomi/aptomi/pkg/api/middleware/recovery.go:40 +0x99
net/http.serverHandler.ServeHTTP(0xc420405930, 0x19ea120, 0xc42071a380, 0xc4208f8700)
/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:2694 +0xbc
net/http.(*conn).serve(0xc42027e1e0, 0x19ecf20, 0xc42034cf40)
/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:1830 +0x651
created by net/http.(*Server).Serve
/usr/local/Cellar/go/1.10.3/libexec/src/net/http/server.go:2795 +0x27b

```

**Comment by rljohnsn** [comment]
Editing my local kubeconfig context to use my laptop IP instead of localhost, allows the aptomi server to connect.

![screen shot 2018-12-12 at 9 31 23 am](https://user-images.githubusercontent.com/830382/49887263-bffff080-fdf0-11e8-9fe9-8c8d139caf85.png)
